import { EffectType as ET, type EffectType } from './types';

export const EFFECT_FA_ICON_CLASS: Partial<Record<EffectType, string>> = {
  [ET.BARRIER]: 'fa-brands fa-fediverse',
  [ET.ARMOR]: 'fa-solid fa-shield-halved',
  [ET.BIND]: 'fa-solid fa-link',
  [ET.DEVOUR]: 'fa-brands fa-optin-monster',
  [ET.POISON]: 'fa-solid fa-virus',
  [ET.POISON_AMOUNT]: 'fa-solid fa-bacterium',
  [ET.CORROSION]: 'fa-brands fa-cloudscale',
  [ET.BURN]: 'fa-solid fa-fire',
  [ET.BLEED]: 'fa-solid fa-droplet',
  [ET.VULNERABLE]: 'fa-brands fa-linode',
  [ET.ORGASM]: 'fa-solid fa-bullseye',
  [ET.DAMAGE_BOOST]: 'fa-brands fa-superpowers',
  [ET.REGEN]: 'fa-brands fa-medrt',
  [ET.SELF_REPAIR]: 'fa-solid fa-gear',
  [ET.WHITE_TURBID]: 'fa-solid fa-droplet',
  [ET.IGNITE_AURA]: 'fa-solid fa-fire-flame-simple',
  [ET.STUN]: 'fa-solid fa-spiral',
  [ET.CHARGE]: 'fa-solid fa-exclamation',
  [ET.FATIGUE]: 'fa-solid fa-bed',
  [ET.COLD]: 'fa-regular fa-snowflake',
  [ET.TEMPERATURE_DIFF]: 'fa-brands fa-empire',
  [ET.NON_LIVING]: 'fa-solid fa-skull',
  [ET.NON_ENTITY]: 'fa-solid fa-ghost',
  [ET.ILLUSORY_BODY]: 'fa-solid fa-ghost',
  [ET.TEMP_MAX_HP]: 'fa-solid fa-heart',
  [ET.MAX_HP_REDUCTION]: 'fa-solid fa-heart-pulse',
  [ET.POINT_GROWTH_BIG]: 'fa-solid fa-dice fa-lg',
  [ET.POINT_GROWTH_SMALL]: 'fa-solid fa-dice fa-sm',
  [ET.MANA_DRAIN]: 'fa-solid fa-battery-empty',
  [ET.MANA_SPRING]: 'fa-brands fa-drupal',
  [ET.SWARM]: 'fa-solid fa-bugs',
  [ET.BLOOD_COCOON]: 'fa-brands fa-battle-net',
  [ET.INDOMITABLE]: 'fa-solid fa-shield',
  [ET.PEEP_FORBIDDEN]: 'fa-solid fa-eye',
  [ET.BLIND_ASH]: 'fa-regular fa-eye-slash',
  [ET.COGNITIVE_INTERFERENCE]: 'fa-solid fa-hamsa',
  [ET.MEMORY_FOG]: 'fa-brands fa-phabricator',
  [ET.SILENCE]: 'fa-solid fa-ban',
  [ET.CONTROLLED]: 'fa-solid fa-face-dizzy',
  [ET.STURDY]: 'fa-solid fa-user-shield',
  [ET.SHOCK]: 'fa-solid fa-bolt',
  [ET.FLAME_ATTACH]: 'fa-solid fa-flask-vial',
  [ET.POISON_ATTACH]: 'fa-solid fa-flask-vial',
  [ET.TOXIN_SPREAD]: 'fa-brands fa-hornbill',
  [ET.AMBUSH]: 'fa-solid fa-user-secret',
  [ET.FROST_ATTACH]: 'fa-solid fa-flask-vial',
  [ET.BLOODBLADE_ATTACH]: 'fa-solid fa-flask-vial',
  [ET.LIGHTNING_ATTACH]: 'fa-solid fa-flask-vial',
  [ET.THORNS]: 'fa-solid fa-leaf',
  [ET.INK_CREATION]: 'fa-solid fa-feather-pointed',
  [ET.MIND_READ]: 'fa-solid fa-brain',
  [ET.ELEMENTAL_ADAPTATION]: 'fa-solid fa-atom',
  [ET.ELEMENTAL_CORTEX]: 'fa-solid fa-atom',
  [ET.MATERIALIZATION]: 'fa-solid fa-person',
};

export const EFFECT_FA_ICON_STYLE: Partial<Record<EffectType, Record<string, string>>> = {
  [ET.FLAME_ATTACH]: { color: 'rgb(255, 64, 64)' },
  [ET.POISON_ATTACH]: { color: 'rgb(81, 255, 116)' },
  [ET.FROST_ATTACH]: { color: 'rgb(108, 230, 255)' },
  [ET.BLOODBLADE_ATTACH]: { color: 'rgb(176, 0, 0)' },
  [ET.LIGHTNING_ATTACH]: { color: 'rgb(201, 69, 255)' },
  [ET.TEMP_MAX_HP]: { color: 'rgb(255, 120, 150)' },
  [ET.ILLUSORY_BODY]: {
    '--fa-primary-color': 'rgb(255, 255, 255)',
    '--fa-secondary-color': 'rgb(255, 255, 255)',
  },
};

export const getEffectFontAwesomeClass = (type: EffectType): string | null => EFFECT_FA_ICON_CLASS[type] ?? null;
export const getEffectFontAwesomeStyle = (type: EffectType): Record<string, string> | undefined => EFFECT_FA_ICON_STYLE[type];
